### PR TITLE
deepcore barrel model 2017

### PR DESCRIPTION
**Pull request by vberta**
Trained model for DeepCoreSeedGenerator, trained in 2019 on MC 2017. Barrel-only training. 
for more info: https://twiki.cern.ch/twiki/bin/view/CMSPublic/NNJetCoreAtCtD2019
related to the PR: https://github.com/cms-sw/cmssw/pull/32222

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
merge

**Comment by silviodonato** [comment]
@smuzaffar @mrodozov there is no cmsdist PR yet

**Comment by mrodozov** [comment]
let me see if it has something to do with the 'main' branch regarding the master->main expected substitutes

**Comment by mrodozov** [comment]
yes, the job failed I need a sec to figure it how to put master OR main

**Comment by mrodozov** [comment]
@silviodonato fixed. its works also with main now

**Comment by silviodonato** [comment]
> @silviodonato fixed. its works also with main now

Thank you!

**Pull request merged**
