### PR TITLE
Adding Latest DeepCore Barrel Training (2022 conditions)

### PR DESCRIPTION
**Pull request by bouchamaouihichem**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@bouchamaouihichem , is there any cms-sw/cmssw PR to test/use this new data file?

**Comment by mmusich** [comment]
@smuzaffar @bouchamaouihichem

> is there any cms-sw/cmssw PR to test/use this new data file?

I provided a cmssw PR to test this:  https://github.com/cms-sw/cmssw/pull/38169
Unfortunately it seems the protobuffer file proposed here is corrupt, see: https://github.com/cms-sw/cmssw/pull/38169#issue-1255888519

**Comment by smuzaffar** [comment]
ping, any update here? This has been pending since a year now

**Comment by mmusich** [comment]
> ping, any update here? This has been pending since a year now

Will be updated in due time.  We're waiting on new samples: https://its.cern.ch/jira/browse/PDMVMCPROD-83

**Comment by mmusich** [comment]
this PR is superseded by https://github.com/cms-data/RecoTracker-TkSeedGenerator/pull/3

**Comment by mmusich** [comment]
@cmsbuild, please close

**Pull request closed without merging**
